UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0876543'
WHERE LICENSE_ID = 1;

UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0123456'
WHERE LICENSE_ID = 2;

UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0976321'
WHERE LICENSE_ID = 3;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0762957'
WHERE LICENSE_ID = 4;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0130002'
WHERE LICENSE_ID = 5;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0364560'
WHERE LICENSE_ID = 6;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0345340'
WHERE LICENSE_ID = 7;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0863576'
WHERE LICENSE_ID = 8;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0144218'
WHERE LICENSE_ID = 9;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0175806'
WHERE LICENSE_ID = 10;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0162174'
WHERE LICENSE_ID = 11;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0247268'
WHERE LICENSE_ID = 12;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0892833'
WHERE LICENSE_ID = 13;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0730318'
WHERE LICENSE_ID = 14;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0970673'
WHERE LICENSE_ID = 15;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0213000'
WHERE LICENSE_ID = 16;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0360227'
WHERE LICENSE_ID = 17;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0351229'
WHERE LICENSE_ID = 18;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0355243'
WHERE LICENSE_ID = 19;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0214401'
WHERE LICENSE_ID = 20;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0239342'
WHERE LICENSE_ID = 21;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0144218'
WHERE LICENSE_ID = 22;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0198040'
WHERE LICENSE_ID = 23;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0543271'
WHERE LICENSE_ID = 24;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0231350'
WHERE LICENSE_ID = 25;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0684956'
WHERE LICENSE_ID = 26;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0675570'
WHERE LICENSE_ID = 27;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0999049'
WHERE LICENSE_ID = 28;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0641414'
WHERE LICENSE_ID = 29;
UPDATE DRIVING_LICENSE
SET LICENSE_NO = 'P0600229'
WHERE LICENSE_ID = 30;


UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 1;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 2;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 3;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 4;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 5;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 6;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 7;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 8;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 9;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 10;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 11;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 12;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 13;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 14;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 15;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 16;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 17;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 18;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 19;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 20;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 21;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 22;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 23;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 24;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 25;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 26;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 27;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 28;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 29;
UPDATE CRIMINAL_RECORDS
SET CASH_AMOUNT  = 100,
  PENALTY_POINTS = 5,
  ISSUE_DATE = to_date('2018-01-01', 'YYYY-MM-DD'),
  DESCRIPTION = 'Przyczyna wystawienia mandatu'
WHERE record_id = 30;


